book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_new_student', views.add_new_student, name='add_new_student'),
    path('add_new_book', views.add_new_book, name='add_new_book'),
    path('add_book_issue', views.add_book_issue, name='book_issue'),
    # path('add_new_book_instance', views.add_new_book_instance, name='add_new_book_instance'),
    path('show_students', views.view_students, name='show_student_record'),
    path('view_books', views.view_books, name='view_books'),
    path('view_books_issued', views.view_bissue, name='show_issue_record'),
    path('book_search', views.book_search, name='book_search'),
    path('borrow/<int:book_id>/', views.borrow_book, name='borrow_book'),
    # path('return/<int:book_id>/', views.return_book, name='return_book'),
    # path('edit_book/<int:id>',views.edit_book,name='edit_book'),
    # path('delete_book/<int:id>',views.delete_book,name='delete_book'),
    # path('edit/student/<str:roll>',views.edit_student_data,name="Edit Student data"),
    # path('edit/book/<uuid:id>',views.edit_book_data,name="Edit Student data"),
    # path('delete/student/<str:roll>',views.delete_student,name="Delete Student data"),
    # path('delete/book/<str:id>',views.delete_book,name="Delete book data"),
    # path('return_book/<int:id>',views.return_issued_book,name="return_issued_book"),
    # path('edit_issued/<int:id>',views.edit_issued,name="edit_issued"),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('first_app.urls'))
]

book/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=100)
    author=models.CharField(max_length=100)
    isbn=models.CharField(max_length=13)
    publication_date=models.DateField(null=True,auto_now_add=True)
    genre=models.CharField(max_length=100)
    quantity=models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title

class BookInstance(models.Model):
    id=models.IntegerField(primary_key=True)
    book=models.ForeignKey(Book, on_delete=models.CASCADE,null=True)
    book_number=models.PositiveIntegerField(null=True)
    Is_borrowed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.id} {self.book}"

class Students(models.Model):
    roll_number = models.CharField(max_length=100,unique=True)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    Email=models.EmailField(max_length=100)
    def __str__(self):
        return self.fullname
    


class Book_Issue(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE)
    book_instance = models.ForeignKey(BookInstance, on_delete=models.CASCADE)
    issue_date = models.DateTimeField(auto_now=True)
    remarks_on_issue = models.CharField(max_length=100)
    remarks_on_return = models.CharField(max_length=100)


class Borrowing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrowed_date = models.DateTimeField(auto_now_add=True)
    returned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} borrowed {self.book.title}"

    class Meta:
        ordering = ['-borrowed_date']


# class Wishlist(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     books = models.ManyToManyField('Book', blank=True)

#     def __str__(self):
#         return self.user.username + "'s Wishlist"
    
    
# class Review(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     book = models.ForeignKey('Book', on_delete=models.CASCADE)
#     content = models.TextField()
#     timestamp = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"Review by {self.user.username} for {self.book.title}"
    
    

book/forms.py
from django import forms 
from book.models import Book,BookInstance,Students,Book_Issue

class BookStoreForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['id','title','author','isbn']
        
        
class Book_instanceForm(forms.ModelForm):
    class Meta:
        model=BookInstance
        fields = ['book','book_number']
        
        
class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'
        
        
class Book_IssueForm(forms.ModelForm):
    class Meta:
        model=Book_Issue
        exclude = ['issue_date','remarks_on_return',]

book/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Book
from book.forms import BookStoreForm,Book_instanceForm,StudentsForm,Book_IssueForm
from book.models import Book,BookInstance,Book_Issue,Students,Borrowing
from django.http import HttpResponse

# Create your views here.
def add_new_student(request):
    if request.method=="POST":
        form = StudentsForm((request.POST))
        if form.is_valid():
            form.save()
            return redirect('/show_students')
    else:
        form = StudentsForm
    return (render(request, 'book/add_new_student.html', {'form':form}))



def add_new_book(request):
    if request.method=="POST":
        form = BookStoreForm(request.POST)
        if form.is_valid():
            form=form.save()
            book_instance=BookInstance(book=form)
            book_instance.save()
            return redirect('/view_books')
    else:
        form = BookStoreForm
        form_instance=Book_instanceForm
        return render(request, 'book/add_new_book.html', {'form':form,"form_instance":form_instance})

def view_books(request):
    books=BookInstance.objects.all()
    return render(request,'book/view_books.html', {'books': books})


def add_book_issue(request):
    if request.method=="POST":
        form = Book_IssueForm(request.POST)
        if form.is_valid():
            # save data
            unsaved_form=form.save(commit=False)
            book_to_save=BookInstance.objects.get(id=unsaved_form.book_instance.id)
            book_to_save.Is_borrowed=True
            book_to_save.save()
            form.save()
            form.save_m2m()
        return redirect('/view_books')
    else:
        context={'form':Book_IssueForm,"book":BookInstance.objects.filter(Is_borrowed=False)}
        return render(request, 'book/add_book_issue.html',context=context)


def view_students(request):
    students = Students.objects.order_by('-id')
    return render(request,'book/view_students.html', {'students': students})

def view_books(request):
    books=BookInstance.objects.order_by('id')
    return render(request,'book/view_books.html', {'books': books})

def view_bissue(request):
    issue = Book_Issue.objects.order_by('-id')
    return render(request,'book/issue_records.html', {'issue': issue})

def add_new_book_instance(request):
    form=Book_instanceForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('/view_books')

def return_issued_book(request,id):   
    obj=Book_Issue.objects.get(id=id)
    return HttpResponse(f"<h2>Return Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be returned..</label>")

def edit_issued(request, id):
    obj=Book_Issue.objects.get(id=id)
    return HttpResponse(f"<h2>Edit Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be edited..</label>")


def borrow_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)

    if book.quantity > 0:
        # Create a borrowing record
        Borrowing.objects.create(user=request.user, book=book)

        # Update the book's quantity
        book.quantity -= 1
        book.save()

        # Redirect to a success page or book detail page
        return redirect('view_books', book_id=book.id)
    else:
        # Handle the case when the book is not available
        # You may want to display a message to the user
        return render(request, 'book_not_available.html')


# def return_book(request, book_id):
#     book = get_object_or_404(Book, pk=book_id)

#     # Check if the user has borrowed this book
#     borrowing = Borrowing.objects.filter(user=request.user, book=book, returned=False).first()

#     if borrowing:
#         # Record the return transaction
#         borrowing.returned = True
#         borrowing.save()

#         # Update the book's quantity
#         book.quantity += 1
#         book.save()

#         # Create a book review if desired
#         review_content = request.POST.get('review_content', '')
#         if review_content:
#             Review.objects.create(user=request.user, book=book, content=review_content)

#         # Redirect to a success page or book detail page
#         return redirect('book_detail', book_id=book.id)
#     else:
#         # Handle the case when the user has not borrowed this book
#         # You may want to display a message to the user
#         return render(request, 'book_not_borrowed.html')



def book_search(request):
    query = request.GET.get('q')  # Get the search query from the URL parameter
    books = Book.objects.filter(title__icontains=query) if query else []
    return render(request, 'book_search.html', {'books': books, 'query': query})


# def view_wishlist(request):
#     # Get the user's wishlist
#     wishlist, created = Wishlist.objects.get_or_create(user=request.user)

#     return render(request, 'library/wishlist.html', {'wishlist': wishlist})


# def add_to_wishlist(request, book_id):
#     book = get_object_or_404(Book, pk=book_id)
#     wishlist, created = Wishlist.objects.get_or_create(user=request.user)
#     wishlist.books.add(book)
#     return redirect('view_wishlist')

# def remove_from_wishlist(request, book_id):
#     book = get_object_or_404(Book, pk=book_id)
#     wishlist = Wishlist.objects.get(user=request.user)
#     wishlist.books.remove(book)
#     return redirect('view_wishlist')

book/templates/book/add_book_issue.html
<title>Add Book Issue</title>
{% extends 'base.html' %}

<body>
{% block content %}

<form method="POST" action="add_book_issue" class="form-inline">
    {% csrf_token %}
    <label>Student Details(Name)</label><br>
    <div id="student_selection">
        <div>{{form.student}}</div>
            <div><input type="text" placeholder="Quick Student Search" id="quick" onkeyup="Quick_search()">
                <div id="quick_student_search_view"></div>
            </div>
    </div>

    <br>
    <hr>
    <div class="book_selection">
        <label>Book Details(Name/UUID)</label>
        <br>
        <div><input type="text" placeholder="Quick Book Search" id="quick_book_search" onkeyup="Quick_book_search()">
            <div id="quick_book_search_view"></div>
        </div>
        <select name="book_instance" required id="id_book_instance">
            <option value="" selected>---------</option>
            {%for i in book%}
                <option class="selection" value="{{i.id}}">{{i.book.book_title}} (: {{i.id}})</option>
            {%endfor%}
        </select>
    </div>
<hr>
    <label>Remarks</label><br> <div> {{form.remarks_on_issue}}</div>
    <br> 
    <button type="submit" class="btn btn-success">Issue Book</button>

</form>


<script type="text/javascript">
    function Quick_search(){
        var input, items,view;
        input = document.getElementById('quick').value.toLowerCase();
        items = document.getElementById('id_student');
        view=document.getElementById("quick_student_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if(input !== "" && (item.toLowerCase().indexOf(input)>-1 )){
                    var list_added = document.createElement("label");
                    list_added.appendChild(document.createTextNode(item));
                    list_added.onclick =function(){
                        items.children[get_clicked_value(this.innerHTML)].setAttribute("selected",true);
                        view.style.display="none";
                        // uncomment below line to hide the search input after selection is made
                        // document.getElementById('quick').style.display="none";
                    };
                    view.appendChild(list_added);
                    view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function get_clicked_value(clicked){
        var items = document.getElementById('id_student');
        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i];
                if (item.innerHTML == clicked ) {
                    return item.getAttribute("value");
                }
        }
    }

    // Quick book search
    function Quick_book_search(){
        var input, items,view;
        input = document.getElementById('quick_book_search');
        items = document.getElementById('id_book_instance');
        view=document.getElementById("quick_book_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if((input.value.toLowerCase() !== "") && (item.toLowerCase().indexOf(input.value.toLowerCase())>-1 ) ){
                var list_added = document.createElement("label");
                list_added.appendChild(document.createTextNode(item));
                list_added.onclick =function(){
                    select_clicked_book(this.innerHTML);
                    view.style.display="none";
                    // comment below line to unhide the search input after selection is made
                    input.style.display="none"; input.value="";
                };
                view.appendChild(list_added);
                view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function select_clicked_book(clicked){
        var books = document.getElementById('id_book_instance');   
        for(i=1;i<books.children.length.valueOf();i++){
            var item=books.children[i];
                if (item.innerHTML == clicked ) {
                    item.setAttribute("selected",true);
                }
        }
    }
</script>
{% endblock %}
</body>
</html>

book/templates/book/add_new_book.html
{% extends 'base.html' %}

<body>
{% block content %}

    <div class="tablinks">
        <button onclick="opentab(name)" class="link" name="new_book">New Book</button>
        <button onclick="opentab(name)" class="link" name="new_book_instance">New Book Instance</button>
    </div>

    <div id="new_book" class="books">
        <form method="POST" action="add_new_book" class="form-inline">
            {% csrf_token %}
        <label>Book Title.</label><br><div>{{form.title}}</div>
        <label>Book Author.</label><br> <div> {{form.author}}</div>
        <label>ISBN.</label><br> <div> {{form.isbn}}</div>
        <br> <button type="submit" class="btn btn-success">Add Book</button> 
        </form>
    </div>
    <br>
    <div id="new_book_instance" class="books">
    <form method="POST" action="add_new_book_instance" class="form-inline">
        {% csrf_token %}
        <label>Book</label><br><div>{{form_instance.book}}</div>
        <label>Book Number</label>
        <div>{{form_instance.book_number}}</div>
        <br> <button type="submit" class="btn btn-success">Add Book</button> 
    </form>
    </div>

<script type="text/javascript">
    function opentab(tab_name){
         var tab=document.getElementById(tab_name);
         var i, tabcontent, tablinks;
         tabcontent = document.getElementsByClassName("books");
         for (i = 0; i < tabcontent.length; i++) {
             tabcontent[i].style.display = "none";
         }
         tablinks = document.getElementsByClassName("link");
         for (i = 0; i < tablinks.length; i++) {
             tablinks[i].className = tablinks[i].className.replace(" active", "");
         }
         tab.style.display = "block";

    }

</script>

{% endblock %}
</body>

</html>

book/templates/book/add_new_student.html
<title>Add New Student</title>
{% extends 'base.html' %}

<body>
    
{% block content %}
<div class="form">
<form method="POST" action="add_new_student" >
    {% csrf_token %}
    <label class="label-default">Student Details</label><br>
    <label>Roll Number:</label><br><div>{{form.roll_number}}</div>
    <label>Student Name:</label><br> <div> {{form.fullname}}</div>
    <label>Student Address:</label><br> <div> {{form.address}}</div>
    <label>Valid Email:</label><br> <div>{{form.Email}}</div>
    <br> <button type="submit" class="btn btn-success">Add Student</button>
</form>
</div>
{% endblock %}

</body>
</html>

book/templates/book/book_not_available.html
<!-- book_not_available.html -->
{% extends 'base.html' %}

{% block title %}Book Not Available{% endblock %}

{% block content %}
    <h1>Book Not Available</h1>
    <p>Sorry, the book is currently not available for borrowing.</p>
    <!-- Provide additional information or links if needed -->
{% endblock %}

book/templates/book/book_search.html
{% extends 'base.html' %}

{% block content %}
    <h1>Search Results for "{{ query }}"</h1>
    <ul>
        {% for book in books %}
            <li>{{ book.title }} by {{ book.author }}</li>
        {% empty %}
            <li>No results found</li>
        {% endfor %}
    </ul>
{% endblock %}

book/templates/book/borrow_book.html
<!-- borrow_book.html -->
{% extends 'base.html' %}

{% block title %}Borrow Book{% endblock %}

{% block content %}
    <h1>Borrow Book</h1>
    <form method="post">
        {% csrf_token %}
        <!-- Add input fields for book details, e.g., book title and author -->
        <label for="book_title">Book Title:</label>
        <input type="text" name="book_title" id="book_title" required>
        
        <label for="book_author">Book Author:</label>
        <input type="text" name="book_author" id="book_author" required>

        <button type="submit">Borrow</button>
    </form>
{% endblock %}

book/templates/book/issue_records.html
<title> Issue Records </title>
{% extends 'base.html' %}

<body>
{% block content %}
<table class="table table-striped">
<tr>
    <th>Student name </th>
    <th>Book ID </th>
    <th>Issue Date </th>
    <th>Due Date</th>
    <th>Remarks on Issuing</th>
    <th>Remarks on Return</th>
    <th>Returned</th>
    <th>Actions</th>
</tr>
    {%for i in issue%}
    <tr>
        <td>{{i.student}}</td>
        <td>{{i.book_instance.id}}</td>
        <td>{{i.issue_date}}</td>
        <td>{{i.due_date}}</td>
        <td>{{i.remarks_on_issue}}</td>
        <td>{{i.remarks_on_return}}</td>
        <td>
            {%if i.book_instance.Is_borrowed %}
            <span><i class="fa fa-times-circle" style="color:rgb(128, 28, 0)"></i></span>
            <td>
                <a href="return_book/{{i.id}}"><i class="fa fa-arrow-alt-circle-right"></i><i class="fa fa-book"></i></a>|
                <a href="edit_issued/{{i.id}}"><i class="fa fa-edit"></i> </a>
            </td>
            {%else%}
            <span><i class="fa fa-check-circle" style="color:green"></i></span>
            <td><a href="edit_issued/{{i.id}}"><i class="fa fa-edit"></i> </a> | <a href="delete_issued/{{i.id}}"><i class="fa fa-trash-alt"></i></a></td>
            {%endif%}
        </td>

        
        
    </tr> {% endfor %}
</table>

{% endblock %}
</body>
</html>

book/templates/book/return_book.html
<!-- return_book.html -->
{% extends 'base.html' %}

{% block title %}Return Book{% endblock %}

{% block content %}
    <h1>Return Book</h1>
    <form method="post">
        {% csrf_token %}
        <!-- Add input fields for book details, e.g., book title and author -->
        <label for="book_title">Book Title:</label>
        <input type="text" name="book_title" id="book_title" required>
        
        <label for="book_author">Book Author:</label>
        <input type="text" name="book_author" id="book_author" required>

        <!-- Optionally, add an input field for the book review -->
        <label for="review_content">Book Review:</label>
        <textarea name="review_content" id="review_content"></textarea>

        <button type="submit">Return</button>
    </form>
{% endblock %}

book/templates/book/view_books.html
<title>Books</title>
{% extends 'base.html' %}

<body>
{% block content %}
<div class="search">
    <input type="text" class="form-control" id="books_search_input" name="book_name" placeholder="Search a book" onkeyup="search_books()">
    <!-- <br> -->
    <div id="book_searched">
        <label>Search Results</label>
    </div>
</div>

<div style="width: 150%; margin: auto">
    <table class="table table-striped">
        <tr>
            <th>Book ID</th>
            <th>title </th>
            <th>author </th>
            <th>Book Number </th>
        </tr>
            {%for book in books%}
            <tr class="book_row">
            <td >{{book.id}}</td>
            <td class="title">{{book.book.title}}</td>
            <td>{{book.book.author}}</td>
            <td >{{book.book_number}}</td>
            <td>
                {%if  book.Is_borrowed %}
                <span><i class="fa fa-times-circle" style="color:rgb(128, 28, 0)"></i></span>
                <td>
                    <a href="edit/book/{{book.id}}"><i class="fa fa-edit"></i></a>
                    </td>
                {%else%}
                <span><i class="fa fa-check-circle" style="color:green"></i></span>
                <td><a href="edit/book/{{book.id}}"><i class="fa fa-edit"></i></a> | <a
                    href="delete/book/{{book.id}}"><i class="fa fa-trash-alt"></i></a></td>
                {%endif%}
            </td>
        
            </tr> {% endfor %}
        </table>
</div>

{% comment %} <script type="text/javascript">
    function search_books(){
    var input, books,view;
    input = document.getElementById('books_search_input').value.toLowerCase();
    books = document.getElementsByClassName('book_row');
    view=document.getElementById("book_searched");
    view.replaceChildren("");

    for(i=0;i<books.length;i++){
        if(input !== ""){
            if (books[i].innerHTML.toLowerCase().indexOf(input)>-1 ) {
                var book_title = document.createTextNode(books[i].getElementsByClassName("title").item(0).textContent);
                var link=document.createElement("a");
                link.setAttribute("href","#"+books[i].getElementsByClassName("title").item(0).textContent);
                
                var list_added = document.createElement("li");
                list_added.appendChild(book_title);
                link.appendChild(list_added);
                view.appendChild(link);
                view.style.display="block";
            }
        }
        else{
            view.style.display="none";
        }
    }
}

</script> {% endcomment %}

{% endblock %}
</body>
</html>

book/templates/book/view_students.html
<title>Student</title>
{% extends 'base.html' %}

<body>
{% block content %}
<div id="message">
    {{message}}
</div>
<div class="search">
    <input type="text" class="form-control" id="student_search_input" name="student_name" placeholder="Search student" onchange="search_student()">
    <!-- <br> -->
    <div id="view_searched">
        <label>Search Results</label>
    </div>
</div>
<div style="width: 150%; margin: auto">
    <table class="table table-striped">
        <tr>
            <th>Roll no </th>
            <th>Name </th>
            <th>Address </th>
            <th>Email</th>
        </tr>
            {%for student in students%}
            <tr id="{{student.fullname}}" class="student">
            <td class="roll_number">{{student.roll_number}}</td>
            <td class="name">{{student.fullname}}</td>
                <td>{{student.address}}</td>
                <td>{{student.Email}}</td>
            </tr> {% endfor %}
        </table>
</div>

{% comment %} <script type="text/javascript">

    function search_student(){
    var input, students,view;
    input = document.getElementById('student_search_input').value.toLowerCase();
    students = document.getElementsByClassName('student');
    view=document.getElementById("view_searched");
    view.replaceChildren("");

    for(i=0;i<students.length;i++){
        if(input !== ""){
            if (students[i].innerHTML.toLowerCase().indexOf(input)>-1 ) {
                var student_name = document.createTextNode(students[i].getElementsByClassName("name").item(0).textContent);
                var student_roll_number = document.createTextNode(students[i].getElementsByClassName("roll_number").item(0).textContent);
                var link=document.createElement("a");
                link.setAttribute("href","#"+students[i].getElementsByClassName("name").item(0).textContent);
                
                var list_added = document.createElement("li");
                list_added.appendChild(student_name);
                list_added.appendChild(student_roll_number);
                link.appendChild(list_added);
                view.appendChild(link);
                view.style.display="block";
            }
        }
        else{
            view.style.display="none";
        }
    }
}

</script> {% endcomment %}
{% endblock %}
</body>
</html>

book/templates/book/wishlist.html
{% extends 'base.html' %}

{% block content %}
    <h1>My Wishlist</h1>
    <ul>
        {% for book in wishlist.books.all %}
            <li>
                {{ book.title }} by {{ book.author }}
                <form method="post" action="{% url 'remove_from_wishlist' book.id %}">
                    {% csrf_token %}
                    <button type="submit">Remove</button>
                </form>
            </li>
        {% empty %}
            <li>Your wishlist is empty.</li>
        {% endfor %}
    </ul>
{% endblock %}